CC=gcc-4.8
CFLAGS= -Wall

all: make

make: svm_inference.o
	$(CC) svm_inference.o -o svm_inference

svm_interference.o : svm_inference.c
	$(CC) $(CFLAGS) -c svm_inference.c

read_cvs_files.o : read_cvs_files.c
	$(CC) $(CFLAGS) -c read_cvs_files.c
