ACCEL_NAME = feature_extraction
SRCS = feature_extraction.c kiss_fft.c eispack.c
#export WORKLOAD=process_data sqrt log10 kiss_fft kiss_fft_stride kw_work
export WORKLOAD=process_data

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
