ACCEL_NAME = feature_extraction
SRCS = feature_extraction.c kiss_fft.c eispack.c
#export WORKLOAD=process_data,pythag,r8_epsilon,r8_max,r8_min,r8_sign,rs,tqlrat,trbak1,tred1,kiss_fft,kiss_fft_stride,kf_bfly2,kf_bfly3,kf_bfly4,kf_bfly5,kf_bfly_generic,kf_work,kf_factor
export WORKLOAD=process_data

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
